server:
  port: 3000

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      start-sage: start-saga-v1
      notify-ending: start-ending-v1
    consumer:
      group-id: order-group
      auto-offset-reset: latest
  data:
    mongodb:
      database: admin
      uri: ${MONGODB_URI:mongodb://admin:123456@localhost:27018}

logging:
  level:
    org:
      apache:
        kafka: OFF
